### ISSUE TITLE
Lines added when using shortcut command in python

### ISSUE THREAD

**Issue by yoniwulf** [maptz/maptz.vscode.extensions.customfolding#109]
When I use the regionfolder.wrapWithRegion shortcut keybinding, lines are added to some code outside of the region.

I have some variables that I would like to contain within a region and some functions after the variable declaration lines: 
![image](https://user-images.githubusercontent.com/70230429/212997495-ee29d2ec-95aa-45c1-b90c-480c161cb326.png)
note the comment before each function is exactly one line above the start of that function

when I select the variables (and some other lines around the variables) and use the shortcut keybind, the following happens:
![image](https://user-images.githubusercontent.com/70230429/212997883-48ffc520-4449-414b-8cae-614bb22975d7.png)
note that now the function has been expanded and there are two lines between the comment and the corresponding function. When I press undo, the format goes back to no lines between the comment and function, and the added region (for the variables) remains. this must mean that two operations are happening when the keybind is pressed. 

I have tried to change the keybind to something unique as Control + M and Control + R both have conflicting keybinds, but the problem persists. 

In the meanwhile, manually typing out the region and endregion still works, but having a keybind would be great!

Any advice would be great :)

**Comment by maptz** [comment]
When the wrap with region command is executed, it inserts some text and calls the `editor.action.formatDocument` command. I suspect it's this command that is removing the double space. 

Unfortunately, there's an issue which means that you can't use the region folder with Python's default region folding (based on indentation). That's why it's wiping out existing folds. 

I'm not sure how you've actually got the existing folds to show actually while also having the region folder enabled for Python.
