### ISSUE TITLE
[Feature Request] Support .vue file

### ISSUE THREAD

**Issue by yoyoys** [maptz/maptz.vscode.extensions.customfolding#13]
Nice plugin, would you made this plugin support `.vue` file?

or provide a option to force active on other extensions? (ex: pug?)

**Comment by maptz** [comment]
I'm going to make the model extensible very soon which should allow for an arbitrary number of file types. I haven't quite worked out how to work with mixed language files yet (like .vue) files. The problem is that javascript in `<script>` tags the region text is be different from within `<html>` tags. I'm looking at options currently, and I'll update you soon.

**Comment by maptz** [comment]
Thanks. I've incorporated this in the new version. I went for HTML style regions by default but you can customize the behaviour now.

**Comment by yoyoys** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/22124891/56884668-136f9400-6a9d-11e9-9df0-ab0148e0d22f.png">
Thanks for HTML tags implements.

But the major issue is `.vue` file's script region can't be folded.

Sorry for late with reproduction.
