### ISSUE TITLE
Feature Request: Add an undo region/ remove region

### ISSUE THREAD

**Issue by psycoxer** [maptz/maptz.vscode.extensions.customfolding#48]
Please add a command that will remove the selected region

**Comment by maptz** [comment]
Thanks for the suggestion @psycoxer.

Just to clarify: are you suggesting that the command would delete just the *region tags* (i.e. `//# region`)? Or are you suggesting that issuing the command would delete the section between the start and end tag then (i.e. all code within the region itself?

**Comment by psycoxer** [comment]
> Thanks for the suggestion @psycoxer.
> 
> Just to clarify: are you suggesting that the command would delete just the _region tags_ (i.e. `//# region`)? Or are you suggesting that issuing the command would delete the section between the start and end tag then (i.e. all code within the region itself?

yes, to delete just the region tags

**Comment by maptz** [comment]
Sure. That should be doable.

**Comment by maptz** [comment]
I've included support for a variety of new commands, including deleting the current region tags, in the latest version of the extension (v1.0.11-preview1).

Since I am unable to publish preview versions of the extension and quite a lot of code has changed. I'm keeping this in the preview stack before publishing it to the Marketplace..

If you get a chance, please test this latest version.
