### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by Elwood-P** [maptz/maptz.vscode.extensions.customfolding#52]
Is it possible to get SCSS support?

**Comment by maptz** [comment]
Yes. Will add in the next version

**Comment by maptz** [comment]
I've included `scss` support in the latest version of the extension (v1.0.11-preview1).

Since I am unable to publish preview versions of the extension and quite a lot of code has changed. I'm keeping this in the preview stack before publishing it to the Marketplace..

If you get a chance, please test this latest version.

**Comment by Elwood-P** [comment]
Thanks. I've tested the preview with scss files and it works for me. 👍
