### ISSUE TITLE
Breaks yaml folding

### ISSUE THREAD

**Issue by joshmccleery** [maptz/maptz.vscode.extensions.customfolding#53]
I work with a lot of yaml files. When this extension is enabled, the default folding doesn't work. I removed the default settings for yaml and the folding started working again. It would be helpful to instead be able to use a setting to disable this extension for a specific language.

**Comment by maptz** [comment]
Yes. This is because of issue [#40](https://github.com/maptz/maptz.vscode.extensions.customfolding/issues/40). I'm working with the VS code team on it. 

But you're right, disabling the extension for a specific language would help.

**Comment by maptz** [comment]
I've included the ability to disable the extension for a specific language in the latest version of the extesnion (v1.0.11-preview1). 

Since I am unable to publish preview versions of the extension and quite a lot of code has changed. I'm keeping this in the preview stack before publishing it to the Marketplace. 

If you get a chance, please test this latest version.
