### ISSUE TITLE
Doesn't work for Ansible YAML files

### ISSUE THREAD

**Issue by unikitty37** [maptz/maptz.vscode.extensions.customfolding#55]
When editing an Ansible YAML file using Microsoft's own Ansible extension, pressing ⌃M⌃R produces the message `Maptz Region Folding. No region folding available for language 'ansible'. Check that you have the language extension installed for these files.`

Changing the file's language to YAML allows region folding to work, but loses all the Ansible-specific features.

Please could you add support for Ansible?

(I'm slightly puzzled as to why language-specific support is needed, actually — surely it just folds from the `#region` to the `#endregion`? Is it that it needs to detect that it's in a comment scope?)

**Comment by maptz** [comment]
Hi, 

I'll push this into the next release (might be a few days off, as I've got a few fundamental changes coming to fix other issues). If you want it to work in the meantime, add the following settings:

```
  "[ansible]": {
    foldEnd: "# endregion",
    foldEndRegex: "[\\s]*#[\\s]*endregion",
    foldStart: "# region [NAME]",
    foldStartRegex: "^[\\s]*#[\\s]*region[\\s]*(.*)[\\s]*$"
  }
```

The reason there is language specific support is because comments are different for different folds, and you might want different folding definitions for different fold kinds:

This extension is for creating 'custom' folds on a per-language basis, rather than providing a single default folding strategy across languages,

**Comment by unikitty37** [comment]
Thanks — that's working great 🙂

**Comment by maptz** [comment]
Great. I'm just finalising `1.0.11-preview3`, but this will make it into the next release when it's out.
