### ISSUE TITLE
Removes ability to fold everything else except #region blocks.  Python.

### ISSUE THREAD

**Issue by myusernameisunique** [maptz/maptz.vscode.extensions.customfolding#56]
I like this extension because it gives me the ability to add the #region and #endregion tags around selected text simply by using a chord.  AND it puts the cursor in the right spot so I can add a header, how cool!

BUT... everything other than a region block (e.g. functions, lists, multi-line strings, etc) cannot be folded any more.  Disabling the extension allows them to be fold-able again.

Can you confirm this?

![image](https://user-images.githubusercontent.com/36269418/86976150-73e96f00-c13f-11ea-8b2a-27eefd2c7389.png)

#region

"""
	<-- notice how there is nothing to collapse.
"""
#endregion

def foo():
	"""
		foo
	"""
	bar = [
		"foo",
		"foo",
	]
	bar = {
		0: "foo",
		1: "foo",
	}

#region

foo()

#endregion

**Comment by maptz** [comment]
Hi, 

This is not the desired behaviour, but it is a known issue. It is not an issue for all languages, and you can disable the functionality in a particular language if you want to use the extension in one language, but not another. 

See [Issue #40](https://github.com/maptz/maptz.vscode.extensions.customfolding/issues/40). It's due to the way the VS Code extensions are able to provide folding enhancements and the right solution hasn't yet been implemented by the VS Code team.
