### ISSUE TITLE
can't fold function in PHP files

### ISSUE THREAD

**Issue by alimuzzaman** [maptz/maptz.vscode.extensions.customfolding#74]
If extension enabled functions can't be folded.

**Comment by maptz** [comment]
Can you provide more information on this? Can you give me an example file?

**Comment by TonyGravagno** [comment]
This just started happening to me as well. With the extension disabled, all default PHP folding options are available. When enabled, no folding controls at all display. This is 100% repeatable on disable/enable+reload.  I am not using any custom settings for this extension. I tried setting editor.showFoldingControls=always but it doesn't work when this extension is enabled. I've closed the current workspace, exited and restarted VSCode, even rebooted the PC. No joy.

I doubt this is a clue, but with the extension enabled, if I disable the @builtin PHP Language Basics extension, functions do show the folding controls. I'm assuming this is because at that point PHP is no longer active, so neither is this extension, and it's just showing folding controls based on default handling of braces for any language.

I'm running extension v1.0.15 with VSCode v1.57.1 over Windows. Happy to provide diagnostics and try a beta.
Thanks for this extension!

**Comment by maptz** [comment]
I'll have a look at this this weekend.

**Comment by boettges** [comment]
The issue seems to be that regions defined as `/* #region */` do not/no longer get recognized by VS Code as foldable. However, `#region` still works:
```json
"maptz.regionfolder": {
    "[php]": {
        "foldStartRegex": ";[\\s]*#region[\\s]*(.*)",
        "foldStart": "#region [NAME]",
        "foldEndRegex": ";[\\s]*#endregion",
        "foldEnd": "#endregion",
}
```

**Comment by aeadedoyin** [comment]
> I'll have a look at this this weekend.

Hey @maptz 🎉 
Have you been able to have a look yet, problem still persists for php files, folding completely stops working.
![image](https://user-images.githubusercontent.com/20503883/137519365-ca557e9c-483f-40eb-9e78-0b38f4270909.png)

**Comment by TonyGravagno** [comment]
The comment by @boettges does not seem to be correct:

<details>
<summary>The issue seems to be ...</summary>

> ...that regions defined as `/* #region */` do not/no longer get recognized by VS Code as foldable. However, `#region` still works:
> 
```json
 "maptz.regionfolder": {
     "[php]": {
         "foldStartRegex": ";[\\s]*#region[\\s]*(.*)",
         "foldStart": "#region [NAME]",
         "foldEndRegex": ";[\\s]*#endregion",
         "foldEnd": "#endregion",
 }
```

</details>

----

With the extension enabled, and the JSON from @boettges, this shows a foldable block:

```php
/* ; #region Main */
$foo = true;
/* ; #endregion Main */
```

But the problem remains that just with the extension enabled the default PHP folding is disabled. Simply enable the extension and all of the fold handles disappear.

My related settings:

```json
"[php]": {
        "editor.folding": true,
},
```

@maptz can we help any more with this outside of getting into your code? TYVM!

**Comment by Krokador** [comment]
I've just noticed this happening in my version of VSCode today, too. 
It's quite annoying to have to add region to a function to have to fold it.

> I'll have a look at this this weekend.

Owner said they would look at it over 6 months ago... Figured I'd bump this back up?

**Comment by TonyGravagno** [comment]
I don't think this extension is necessary anymore, except for the benefits of custom folding syntax and multi-language support. Folding now seems to work perfectly in vanilla VSCode, at least for PHP.

<details>
<summary>Note the correct PHP syntax for a region</summary>

```php
    #region Folding major block
    /* Summary for Folding Comments
        Details in here
    */

    /**
           Folding DocBlock
     **/
    function foldingFunction()
    {
        #region Nested region folds too
        // any code here
        #endregion
    }

    #endregion Folding major block
```

</details>

## Screenshots

<details>
<summary>Completely Collapsed</summary>

![image](https://user-images.githubusercontent.com/499473/150622000-dca88f1c-8082-4b3c-af89-a733444a1fc7.png)

</details>

<details>
<summary>Completely Open showing handles</summary>

![image](https://user-images.githubusercontent.com/499473/150622421-ce28b2e5-3c42-43f4-b3b4-f904776eb137.png)


</details>

<details>
<summary>Collapsed nested region (based on spaces)</summary>

![image](https://user-images.githubusercontent.com/499473/150622465-4db7adcc-3a92-47ee-9ba5-655bede4116e.png)

</details>


<details>
<summary>Folding works on functions regardless of placement of braces</summary>

![image](https://user-images.githubusercontent.com/499473/150622184-4cc9907f-cae7-4e0d-ad4b-8a22beb2da35.png)

</details>
