### ISSUE TITLE
Regions no longer folding

### ISSUE THREAD

**Issue by spiercy16** [maptz/maptz.vscode.extensions.customfolding#94]
I've been using your extension for several years without any issues and really appreciate its usefulness. I recently opened one of my SCSS files and noticed that none of the regions were folding. Also, when I went to the extension page in VS Code I noticed the info listed in the "Details" section was now missing, making the extension look abandoned. I have used this extension extensively to markup my files and make them easier to edit and if it's no longer going to be updated, please let me know so that I can look for another solution.

**Comment by maptz** [comment]
Hi, 

There was an issue with 1.0.16. I'm not sure what happened but the version that went to the gallery wasn't working. 

I thought it had been resolved with 1.0.17. Can you check you are running 1.0.17?

**Comment by spiercy16** [comment]
The version currently online in VS Code is 1.0.16. If you could upload the new version ASAP I would really appreciate it. Trying to code in SCSS without it is a real nightmare. Thank you!

**Comment by maptz** [comment]
Can you go to the extensions tab in VS Code and try to update the extension. Version 1.0.17 is on the marketplace, so should download. 

https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder

**Comment by spiercy16** [comment]
That is how I installed it in the first place. It shows that I'm running version 1.0.16 and when I check for extension updates VS Code says that "all extensions are up to date". Also, when I click the link you just posted it takes me to the webpage. When I click the link in there to install it, it opens in my VS Code app and shows that it's the version I already have.

**Comment by maptz** [comment]
Hmm. 

On the marketplace, you should be able to see the latest version which is 1.0.17. See [here](https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder)

I wonder if you are running a previous version of VS Code and that's why you're not being offered the update. v1.0.17 requires engine version 1.65.0 as the previous versions of VS Code were causing the 1.0.16 issue. 

If you don't want to upgrade VS Code, then you can install a previous version by clicking on the dropdown next to `Uninstall` in the VS Code Extension popup. 

![image](https://user-images.githubusercontent.com/18685646/157532747-d81deb81-af42-4461-81d6-9c1dd1ec4865.png)

**Comment by spiercy16** [comment]
I updated VS Code, was able to update the extension, and now it's working. Thanks for the help!
